use crate::cli::sudo;
use std::io::Write;
use std::path::Path;
use std::process::ExitStatus;
use tempfile::NamedTempFile;

const FILE_PATH: &str = "/etc/xbps.d/50-vx-repos.conf";

#[derive(Debug)]
pub struct Repository {
    pub enabled: bool,
    pub url: String,
    pub name: String,
}

pub struct Repositories {
    repos: Vec<Repository>,
}

impl Repositories {
    pub fn open() -> std::io::Result<Repositories> {
        let contents = match std::fs::read_to_string(FILE_PATH) {
            Ok(c) => c,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                let repos = Repositories { repos: vec![] };
                repos.save()?;

                return Ok(repos);
            }
            Err(e) => return Err(e),
        };

        let mut repos = vec![];
        let mut name: Option<String> = None;

        for raw_line in contents.lines() {
            let line = raw_line.trim();

            if line.is_empty() {
                continue;
            }

            if let Some(value) = line.strip_prefix("#name:") {
                name = Some(value.trim().to_string());
                continue;
            }

            let repo = if let Some(value) = line.strip_prefix("repository=") {
                Some((true, value.trim()))
            } else {
                line.strip_prefix("#repository=")
                    .map(|value| (false, value.trim()))
            };

            if let Some((enabled, url)) = repo {
                let url = url.to_string();
                let name = name.take().unwrap_or_else(|| url.clone());

                repos.push(Repository { enabled, url, name });
            }
        }

        Ok(Self { repos })
    }

    pub fn save(&self) -> std::io::Result<ExitStatus> {
        let mut file = NamedTempFile::new()?;
        Self::write_header(&mut file)?;

        for repo in &self.repos {
            writeln!(file, "#name:{}", repo.name)?;

            if repo.enabled {
                writeln!(file, "repository={}", repo.url)?;
            } else {
                writeln!(file, "#repository={}", repo.url)?;
            }

            writeln!(file)?;
        }

        Self::install(file.path()).and_then(|status| {
            if status.success() {
                Ok(status)
            } else {
                Err(std::io::Error::other("failed to install repository file"))
            }
        })
    }

    pub fn add(&mut self, name: impl AsRef<str>, url: impl AsRef<str>, enabled: bool) {
        self.repos.push(Repository {
            name: name.as_ref().to_string(),
            url: url.as_ref().to_string(),
            enabled,
        });
    }

    pub fn remove(&mut self, name: impl AsRef<str>) {
        self.repos.retain(|r| r.name != name.as_ref());
    }

    pub fn enable(&mut self, name: impl AsRef<str>) {
        if let Some(repo) = self.repos.iter_mut().find(|r| r.name == name.as_ref()) {
            repo.enabled = true;
        }
    }

    pub fn disable(&mut self, name: impl AsRef<str>) {
        if let Some(repo) = self.repos.iter_mut().find(|r| r.name == name.as_ref()) {
            repo.enabled = false;
        }
    }

    pub fn iter(&self) -> impl Iterator<Item = &Repository> {
        self.repos.iter()
    }

    fn write_header(mut w: impl Write) -> std::io::Result<()> {
        writeln!(
            w,
            "# This file is automatically generated and managed by vx"
        )?;
        writeln!(w, "# Do not edit unless you REALLY know what you're doing!")?;
        writeln!(w)?;

        Ok(())
    }

    fn install(from: impl AsRef<Path>) -> std::io::Result<ExitStatus> {
        let mut cmd = sudo("install");
        cmd.arg("-D");
        cmd.args(["-m", "0644"]);
        cmd.args(["-o", "root"]);
        cmd.args(["-g", "root"]);
        cmd.arg(from.as_ref());
        cmd.arg(FILE_PATH);

        cmd.status()
    }
}
